## Задача 1

Реализовать класс для работы с линейной регрессией

In [ ]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.model_selection import train_test_split
import time
import matplotlib.pyplot as plt

In [ ]:
class MyLinearRegression:
    """
    Parameters
    ----------
    regularization : {None, 'l1', 'l2', 'l1l2'}, default=None
        Какую регуляризацию добавить к модели. Если значение `None`, то без регуляризации.

    weight_calc : {'matrix', 'gd', 'sgd'}, default='matrix'
        Каким образом вычислять вектор весов: матрично ('matrix'), градиентным спуском ('gd') или стохастическим градиентным спуском ('sgd'). При этом, при 'l1' или 'l1l2' нельзя использовать параметр 'matrix'.

    Attributes
    ----------
    coefs_ : Вектор коэффициентов размера (p, 1), где p — количество признаков.
    intercept_ : Значение коэффициента, отвечающего за смещение
    """

    def __init__(self,
                 regularization=None,
                 weight_calc='matrix',
                 lambda_1=None,
                 lambda_2=None,
                 batch_size=20,
                 max_iter = 10000,
                 alpha=1e-2,
                 early_stopping = 0.001):
        if regularization not in [None, 'l1', 'l2', 'l1l2']:
            raise TypeError(f"Параметр regularization не может принимать значение '{regularization}'")
        if weight_calc not in ['matrix', 'gd', 'sgd']:
            raise TypeError(f"Параметр weight_calc не может принимать значение '{weight_calc}'")
        if regularization in ['l1', 'l1l2'] and lambda_1 is None:
            raise TypeError(f"Значение коэффициента регулризации l1 не задано")
        if regularization in ['l2', 'l1l2'] and lambda_2 is None:
            raise TypeError(f"Значение коэффициента регулризации l2 не задано")

        self.regularization = regularization
        self.weight_calc = weight_calc
        self.lambda_1 = lambda_1
        self.lambda_2 = lambda_2
        self.batch_size = batch_size
        self.coef_ = None
        self.intercept_ = None
        self.alpha = alpha
        self.max_iter = max_iter
        self.early_stopping = early_stopping

    def fit(self, X: pd.DataFrame, y: pd.DataFrame):

        if type(X) != np.ndarray:
            X = X.to_numpy()
        if type(y) != np.ndarray:
            y = y.to_numpy()

        if self.weight_calc == 'matrix':
            self.matrix_method(X, y, self.lambda_1, self.lambda_2)
        elif self.weight_calc == 'gd':
            self.gd(X, y)
        else:
            self.sgd(X, y)


    def matrix_method(self, X, y, lambda_1, lambda_2):
        if self.regularization in ['l1', 'l1l2']:
            raise TypeError("При 'l1' или 'l1l2' нельзя использовать параметр 'matrix'.")
        n,m = X.shape
        X = np.hstack([np.ones((n, 1)), X])
        y = y.reshape(-1, 1)

        if self.regularization == 'l2':
            reg = np.eye((X.T @ X).shape[0])
            theta = np.linalg.inv(X.T @ X + self.lambda_2 * reg) @ X.T @ y
        else:
            theta = np.linalg.inv(X.T @ X) @ X.T @ y

        self.intercept_ = theta[0, 0]
        self.coef_ = theta[1:, 0]

    def gd(self, X, y):

        n, m = X.shape

        # Добавляем столбец единиц для смещения (intercept)
        X = np.hstack([np.ones((n, 1)), X])  # добавляем столбец единичных значений для intercept
        weights = np.random.randn(X.shape[1]) * 0.01  # Инициализация весов случайными малыми значениями

        for i in tqdm(range(self.max_iter)):
            # Предсказания
            predictions = X.dot(weights)

            # Ошибка
            error = predictions - y.flatten()

            # Градиент
            gradients = (2 / n) * X.T.dot(error)

            # Регуляризация
            if self.regularization == 'l1':
                gradients += self.lambda_1 * np.sign(weights)
            if self.regularization == 'l2':
                gradients += 2 * self.lambda_2 * weights
            if self.regularization == 'l1l2':
                gradients += self.lambda_1 * np.sign(weights)
                gradients += 2 * self.lambda_2 * weights

            # Обновляем веса
            weights -= self.alpha * gradients

            # Проверка на малый градиент (early stopping)
            if np.linalg.norm(gradients) < self.early_stopping:
                print(f"Early stopping at iteration {i}")
                break

            # Проверка на NaN в весах и ошибках
            if np.any(np.isnan(weights)) or np.any(np.isnan(error)):
                print(f"NaN encountered at iteration {i}. Stopping.")
                break

            # Проверка на слишком большие значения весов
            if np.any(np.abs(weights) > 1e10):
                print(f"Warning: weights are too large at iteration {i}")
                break

        self.intercept_ = weights[0]  # Первый элемент - это intercept
        self.coef_ = weights[1:]  # Остальные элементы - это коэффициенты для признаков


    def sgd(self, X, y):
        n,m = X.shape

        X = np.hstack([np.ones((n, 1)), X])  # добавляем столбец единичных значений для intercept
        weights = np.random.randn(X.shape[1]) * 0.01

        for i in tqdm(range(self.max_iter)):
            batch_indices = np.random.choice(n, self.batch_size, replace=False)
            X_batch = X[batch_indices]
            y_batch = y[batch_indices]

            #Предсказания
            predictions = X_batch.dot(weights)

            #Ошибка
            error = predictions - y_batch#.flatten()

            #градиент
            gradients = 2 * X_batch.T.dot(error) / self.batch_size

            if self.regularization == 'l1':
                gradients += self.lambda_1 * np.sign(weights)
            if self.regularization == 'l2':
                gradients += 2 * self.lambda_2 * weights
            if self.regularization == 'l1l2':
                gradients += self.lambda_1 * np.sign(weights)
                gradients += 2 * self.lambda_2 * weights

            #обновляем веса
            weights -= self.alpha * gradients

            if np.any(np.isnan(weights)) or np.any(np.isnan(error)):
                print(f"NaN encountered at iteration {i}. Stopping.")
                break

            if np.any(np.abs(weights) > 1e10):
                print(f"Warning: weights are too large at iteration {i}")
                break

            #Проверка, что градиент не маленький
            if np.linalg.norm(gradients) < self.early_stopping:
                print(f"Early stopping at iteration {i}")
                break

        self.intercept_ = weights[0]
        self.coef_ = weights[1:]

    def predict(self, X: np.array, ss=True):
        # print("coef_.shape = ", self.coef_.shape)
        # print("intercept_.shape = ", self.intercept_.shape)
        # print("X= ", X)
        # print("coeff= ", self.coef_)
        # print("intercept= ", self.intercept_)

        # print("type X= ", type(X))
        # print("type coeff= ", type(self.coef_))
        # print("type intercept= ", type(self.intercept_))

        # print("shape X= ", X.shape)
        # print("shape coeff= ", self.coef_.shape)
        # print("shape intercept= ", self.intercept_.shape)

        X_arr = np.array(X, dtype=float)

        if ss:
            return X_arr @ np.asarray(self.coef_) + np.asarray(self.intercept_)
        return X_arr @ np.asarray(self.coef_)

    def score_MSE(self, X: np.array, y: np.array):
        y_pred = self.predict(X)
        return np.mean((y_pred - y) ** 2)

    def score_MAE(self, X: np.array, y: np.array):
        y_pred = self.predict(X)
        return np.mean(np.abs(y_pred - y))

Используя датасет про автомобили (целевой признак — price), сравнить (качество, скорость обучения и предсказания, важность признаков) модели `MyLinearRegression` с различными гиперпараметрами, сделать выводы.

# Задача 2

[Соревнование на Kaggle](https://www.kaggle.com/competitions/stat-plus-ml-2024)

In [ ]:
!unzip /content/ensembles-competition.zip

Archive:  /content/ensembles-competition.zip
  inflating: Sample_Submission.csv   
  inflating: for_prediction.csv      
  inflating: train_contest.csv       


In [ ]:
!pip install unrar
!unrar x /content/kaggle_linreg.rar


UNRAR 6.11 beta 1 freeware      Copyright (c) 1993-2022 Alexander Roshal


Extracting from /content/kaggle_linreg.rar

Extracting  for_prediction.csv                                             0%  1%  2%  3%  4%  5%  6%  7%  8%  9% 10% 11% 12% 13% 14% 15% 16% 17% 18% 19% 20%  OK 
Extracting  Sample_Submission.csv                                         20%  OK 
Extracting  train_contest.csv                                             20% 21% 22% 23% 24% 25% 26% 27% 28% 29% 30% 31% 32% 33% 34% 35% 36% 37% 38% 39% 40% 41% 42% 43% 44% 45% 46% 47% 48% 49% 50% 51% 52% 53% 54% 55% 56% 57% 58% 59% 60% 61% 62% 63% 64% 65% 66% 67% 68% 69% 70% 71% 72% 73% 74% 75% 76% 77

In [ ]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.model_selection import train_test_split
import time
import matplotlib.pyplot as plt

#Предобработка данных

In [ ]:
data_train_orig = pd.read_csv('train_contest.csv')
data_for_pred_orig = pd.read_csv('for_prediction.csv')

data_train = data_train_orig.copy()
data_for_pred = data_for_pred_orig.copy()

In [ ]:
data_train_orig.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30072 entries, 0 to 30071
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   premium                   30072 non-null  bool   
 1   name                      30072 non-null  object 
 2   department                752 non-null    object 
 3   has_test                  30072 non-null  bool   
 4   response_letter_required  30072 non-null  bool   
 5   area                      30072 non-null  object 
 6   type                      30072 non-null  object 
 7   address                   19105 non-null  object 
 8   response_url              0 non-null      float64
 9   sort_point_distance       0 non-null      float64
 10  published_at              30072 non-null  object 
 11  created_at                30072 non-null  object 
 12  archived                  30072 non-null  bool   
 13  insider_interview         94 non-null     object 
 14  url   

In [ ]:
data_train_orig

premium                                               name  \
0        False                              Агент по недвижимости   
1        False                              IT-специалист/ техник   
2        False                Старший/ведущий инженер-программист   
3        False               Эксперт / методист приемной комиссии   
4        False                               Табельщица/табельщик   
...        ...                                                ...   
30067    False                      Руководитель отдела персонала   
30068    False        Специалист по развитию и обучению персонала   
30069    False                                Инженер-программист   
30070    False                                    Куратор проекта   
30071    False  Консультант / Брокер по коммерческой недвижимости   

                                             department  has_test  \
0                                                   NaN     False   
1                                                   NaN     False   
2                                                   NaN     False   
3                                                   NaN     False   
4                                                   NaN     False   
...                                                 ...       ...   
30067                                               NaN     False   
30068                                               NaN     False   
30069                                               NaN     False   
30070  {'id': '1947314-1947314-ancor', 'name': 'ANCOR'}     False   
30071                                               NaN     False   

       response_letter_required  \
0                         False   
1                         False   
2                         False   
3                         False   
4                         False   
...                         ...   
30067                     False   
30068                     False   
30069                     False   
30070                     False   
30071                     False   

                                                    area  \
0      {'id': '2', 'name': 'Санкт-Петербург', 'url': ...   
1      {'id': '1130', 'name': 'Братск', 'url': 'https...   
2      {'id': '76', 'name': 'Ростов-на-Дону', 'url': ...   
3      {'id': '1', 'name': 'Москва', 'url': 'https://...   
4      {'id': '1613', 'name': 'Энгельс', 'url': 'http...   
...                                                  ...   
30067  {'id': '1', 'name': 'Москва', 'url': 'https://...   
30068  {'id': '1641', 'name': 'Набережные Челны', 'ur...   
30069  {'id': '1399', 'name': 'Магнитогорск', 'url': ...   
30070  {'id': '3', 'name': 'Екатеринбург', 'url': 'ht...   
30071  {'id': '1', 'name': 'Москва', 'url': 'https://...   

                                     type  \
0      {'id': 'open', 'name': 'Открытая'}   
1      {'id': 'open', 'name': 'Открытая'}   
2      {'id': 'open', 'name': 'Открытая'}   
3      {'id': 'open', 'name': 'Открытая'}   
4      {'id': 'open', 'name': 'Открытая'}   
...                                   ...   
30067  {'id': 'open', 'name': 'Открытая'}   
30068  {'id': 'open', 'name': 'Открытая'}   
30069  {'id': 'open', 'name': 'Открытая'}   
30070  {'id': 'open', 'name': 'Открытая'}   
30071  {'id': 'open', 'name': 'Открытая'}   

                                                 address  response_url  \
0      {'city': 'Санкт-Петербург', 'street': 'Невский...           NaN   
1                                                    NaN           NaN   
2      {'city': 'Ростов-на-Дону', 'street': '60К-9, 1...           NaN   
3      {'city': 'Москва', 'street': '1-я Миусская ули...           NaN   
4      {'city': None, 'street': None, 'building': Non...           NaN   
...                                                  ...           ...   
30067  {'city': 'Москва', 'street': 'Ленинградский пр...           NaN   
30068  {'city': 'Набережные Челны', 'street': 'проспе...           NaN   


In [ ]:
data_train[(data_train['type'] !=  "{'id': 'open', 'name': 'Открытая'}")]['type']

222      {'id': 'anonymous', 'name': 'Анонимная'}
259      {'id': 'anonymous', 'name': 'Анонимная'}
1538     {'id': 'anonymous', 'name': 'Анонимная'}
1754     {'id': 'anonymous', 'name': 'Анонимная'}
1870     {'id': 'anonymous', 'name': 'Анонимная'}
2020     {'id': 'anonymous', 'name': 'Анонимная'}
2058     {'id': 'anonymous', 'name': 'Анонимная'}
3158     {'id': 'anonymous', 'name': 'Анонимная'}
3196     {'id': 'anonymous', 'name': 'Анонимная'}
4300     {'id': 'anonymous', 'name': 'Анонимная'}
4750     {'id': 'anonymous', 'name': 'Анонимная'}
5461     {'id': 'anonymous', 'name': 'Анонимная'}
6575     {'id': 'anonymous', 'name': 'Анонимная'}
7973     {'id': 'anonymous', 'name': 'Анонимная'}
8182     {'id': 'anonymous', 'name': 'Анонимная'}
8349     {'id': 'anonymous', 'name': 'Анонимная'}
8424     {'id': 'anonymous', 'name': 'Анонимная'}
9273     {'id': 'anonymous', 'name': 'Анонимная'}
9661     {'id': 'anonymous', 'name': 'Анонимная'}
10182    {'id': 'anonymous', 'name': 'Анонимная'}
11426    {'id': 'anonymous', 'name': 'Анонимная'}
11625    {'id': 'anonymous', 'name': 'Анонимная'}
12065    {'id': 'anonymous', 'name': 'Анонимная'}
13028    {'id': 'anonymous', 'name': 'Анонимная'}
13149    {'id': 'anonymous', 'name': 'Анонимная'}
13721    {'id': 'anonymous', 'name': 'Анонимная'}
13982    {'id': 'anonymous', 'name': 'Анонимная'}
14231    {'id': 'anonymous', 'name': 'Анонимная'}
15348    {'id': 'anonymous', 'name': 'Анонимная'}
15405    {'id': 'anonymous', 'name': 'Анонимная'}
15956    {'id': 'anonymous', 'name': 'Анонимная'}
17269    {'id': 'anonymous', 'name': 'Анонимная'}
17536    {'id': 'anonymous', 'name': 'Анонимная'}
18184    {'id': 'anonymous', 'name': 'Анонимная'}
19124    {'id': 'anonymous', 'name': 'Анонимная'}
20440    {'id': 'anonymous', 'name': 'Анонимная'}
20590    {'id': 'anonymous', 'name': 'Анонимная'}
20779    {'id': 'anonymous', 'name': 'Анонимная'}
21333    {'id': 'anonymous', 'name': 'Анонимная'}
22254    {'id': 'anonymous', 'name': 'Анонимная'}
22815    {'id': 'anonymous', 'name': 'Анонимная'}
25296    {'id': 'anonymous', 'name': 'Анонимная'}
25638    {'id': 'anonymous', 'name': 'Анонимная'}
28222    {'id': 'anonymous', 'name': 'Анонимная'}
29415    {'id': 'anonymous', 'name': 'Анонимная'}
29861    {'id': 'anonymous', 'name': 'Анонимная'}
29932    {'id': 'anonymous', 'name': 'Анонимная'}
Name: type, dtype: object

In [ ]:
obj_cols = data_train_orig.select_dtypes(object).columns

for col in obj_cols:
    print(col)
    print(f"Процент пропущенных значений в столбце {col} = {(data_train_orig[col] == '[]').sum()/data_train_orig.shape[0]}")
    print(f"Среднее значение зарплаты для пропущенных = {data_train_orig[data_train[col] == '[]']['mean_salary'].mean()}")
    print(f"Среднее значение зарплаты для присутствующих = {data_train_orig[data_train_orig[col] != '[]']['mean_salary'].mean()}")
    print()

name
Процент пропущенных значений в столбце name = 0.0
Среднее значение зарплаты для пропущенных = nan
Среднее значение зарплаты для присутствующих = 97728.25091447194

department
Процент пропущенных значений в столбце department = 0.0
Среднее значение зарплаты для пропущенных = nan
Среднее значение зарплаты для присутствующих = 97728.25091447194

area
Процент пропущенных значений в столбце area = 0.0
Среднее значение зарплаты для пропущенных = nan
Среднее значение зарплаты для присутствующих = 97728.25091447194

type
Процент пропущенных значений в столбце type = 0.0
Среднее значение зарплаты для пропущенных = nan
Среднее значение зарплаты для присутствующих = 97728.25091447194

address
Процент пропущенных значений в столбце address = 0.0
Среднее значение зарплаты для пропущенных = nan
Среднее значение зарплаты для присутствующих = 97728.25091447194

published_at
Процент пропущенных значений в столбце published_at = 0.0
Среднее значение зарплаты для пропущенных = nan
Среднее значение з

In [ ]:
bool_cols = data_train_orig.select_dtypes(bool).columns

for col in bool_cols:
    print(col)
    print(f"Процент false в столбце {col} = {(data_train_orig[col] == True).sum()/data_train_orig.shape[0]}")
    print(f"Среднее значение зарплаты для True = {data_train_orig[data_train_orig[col] == True]['mean_salary'].mean()}")
    print(f"Среднее значение зарплаты для False = {data_train_orig[data_train_orig[col] == False]['mean_salary'].mean()}")
    print()

premium
Процент false в столбце premium = 0.003391859537110934
Среднее значение зарплаты для True = 143156.86274509804
Среднее значение зарплаты для False = 97573.6390223557

has_test
Процент false в столбце has_test = 0.014032987496674648
Среднее значение зарплаты для True = 133779.65758293838
Среднее значение зарплаты для False = 97215.14151770658

response_letter_required
Процент false в столбце response_letter_required = 0.01646049481245012
Среднее значение зарплаты для True = 102348.42121212122
Среднее значение зарплаты для False = 97650.92784934239

archived
Процент false в столбце archived = 0.00013301409949454643
Среднее значение зарплаты для True = 68000.0
Среднее значение зарплаты для False = 97732.20571704138

accept_temporary
Процент false в столбце accept_temporary = 0.09364192604416068
Среднее значение зарплаты для True = 112245.21608664772
Среднее значение зарплаты для False = 96228.40596565894



Удалим сильно несбалансированные данные, ненужные данные и данные с большими пропусками

In [ ]:
bool_cols = data_train_orig.select_dtypes(bool).columns
unbalanced_data = bool_cols
data_with_lots_nans = ['working_days', 'working_time_intervals', 'working_time_modes', 'relations', 'sort_point_distance', 'insider_interview']
useless_data = ['department', 'response_url', 'immediate_redirect_url', 'type', 'published_at', 'created_at', 'url', 'alternate_url', "address", "contacts"]

In [ ]:
data_train = data_train_orig.drop([*unbalanced_data, *data_with_lots_nans, *useless_data], axis=1)

In [ ]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30072 entries, 0 to 30071
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   name             30072 non-null  object 
 1   area             30072 non-null  object 
 2   employer         30072 non-null  object 
 3   snippet          30072 non-null  object 
 4   schedule         30072 non-null  object 
 5   description      30072 non-null  object 
 6   experience       30072 non-null  object 
 7   key_skills       30072 non-null  object 
 8   specializations  30072 non-null  object 
 9   region           30072 non-null  object 
 10  mean_salary      30072 non-null  float64
dtypes: float64(1), object(10)
memory usage: 2.5+ MB


In [ ]:
data_train_orig[data_train_orig['contacts'].isnull()]['mean_salary'].describe()

count    1.098700e+04
mean     1.013885e+05
std      9.300644e+04
min      6.250000e+01
25%      4.050000e+04
50%      7.000000e+04
75%      1.300000e+05
max      1.100000e+06
Name: mean_salary, dtype: float64

In [ ]:
data_train_orig[data_train_orig['contacts'].notnull()]['mean_salary'].describe()

count    1.908500e+04
mean     9.562109e+04
std      1.106741e+05
min      2.000000e+01
25%      4.250000e+04
50%      6.750000e+04
75%      1.150000e+05
max      2.750000e+06
Name: mean_salary, dtype: float64

In [ ]:
data_train

name  \
0                                  Агент по недвижимости   
1                                  IT-специалист/ техник   
2                    Старший/ведущий инженер-программист   
3                   Эксперт / методист приемной комиссии   
4                                   Табельщица/табельщик   
...                                                  ...   
30067                      Руководитель отдела персонала   
30068        Специалист по развитию и обучению персонала   
30069                                Инженер-программист   
30070                                    Куратор проекта   
30071  Консультант / Брокер по коммерческой недвижимости   

                                                    area  \
0      {'id': '2', 'name': 'Санкт-Петербург', 'url': ...   
1      {'id': '1130', 'name': 'Братск', 'url': 'https...   
2      {'id': '76', 'name': 'Ростов-на-Дону', 'url': ...   
3      {'id': '1', 'name': 'Москва', 'url': 'https://...   
4      {'id': '1613', 'name': 'Энгельс', 'url': 'http...   
...                                                  ...   
30067  {'id': '1', 'name': 'Москва', 'url': 'https://...   
30068  {'id': '1641', 'name': 'Набережные Челны', 'ur...   
30069  {'id': '1399', 'name': 'Магнитогорск', 'url': ...   
30070  {'id': '3', 'name': 'Екатеринбург', 'url': 'ht...   
30071  {'id': '1', 'name': 'Москва', 'url': 'https://...   

                                                employer  \
0      {'id': '541016', 'name': 'АРИН', 'url': 'https...   
1      {'id': '1136625', 'name': 'СМП-38', 'url': 'ht...   
2      {'id': '611346', 'name': 'САРМАТ, НПП', 'url':...   
3      {'id': '171255', 'name': 'РХТУ им. Д.И. Мендел...   
4      {'id': '617150', 'name': 'Сигнал, группа компа...   
...                                                  ...   
30067  {'id': '127256', 'name': 'СИНЕРГИЯ', 'url': 'h...   
30068  {'id': '1068750', 'name': 'Brinex', 'url': 'ht...   
30069  {'id': '824486', 'name': 'Магнитогорский метал...   
30070  {'id': '1947314', 'name': 'ANCOR', 'url': 'htt...   
30071  {'id': '675098', 'name': 'Bright Rich | CORFAC...   

                                                 snippet  \
0      {'requirement': 'Уверенное знание компьютера‚ ...   
1      {'requirement': 'Навыки. Коммуникативные навык...   
2      {'requirement': 'Высшее инженерно-техническое ...   
3      {'requirement': 'Высшее образование. Опыт рабо...   
4      {'requirement': 'Знание в совершенстве програм...   
...                                                  ...   
30067  {'requirement': 'Университетское образование в...   
30068  {'requirement': 'Высшее образование. Опыт рабо...   
30069  {'requirement': 'Опыт работы с базами данных, ...   
30070  {'requirement': 'Опыт личных (очных) продаж от...   
30071  {'requirement': 'Высшее образование/ возможнос...   

                                              schedule  \
0          {'id': 'flexible', 'name': 'Гибкий график'}   
1      {'id': 'flyInFlyOut', 'name': 'Вахтовый метод'}   
2             {'id': 'fullDay', 'name': 'Полный день'}   
3             {'id': 'fullDay', 'name': 'Полный день'}   
4             {'id': 'fullDay', 'name': 'Полный день'}   
...                                                ...   
30067         {'id': 'fullDay', 'name': 'Полный день'}   
30068         {'id': 'fullDay', 'name': 'Полный день'}   
30069         {'id': 'fullDay', 'name': 'Полный день'}   
30070      {'id': 'flexible', 'name': 'Гибкий график'}   
30071         {'id': 'fullDay', 'name': 'Полный день'}   

                                             description  \
0      <p>Мы ищем людей, которым не достаточно того, ...   
1      <ul> </ul> <p><em><strong>Навыки</strong></em>...   
2      <strong>Обязанности:</strong> <ul> <li>Разрабо...   
3      <p>Департамент информационных технологий РХТУ ...   
4      <p><strong>Обязанности:</strong></p> <ul> <li>...   
...                                                  ...   
30067  <strong>Обязанности:</strong> <ul> <li>Управ

In [ ]:
data_train_orig['schedule']

0            {'id': 'flexible', 'name': 'Гибкий график'}
1        {'id': 'flyInFlyOut', 'name': 'Вахтовый метод'}
2               {'id': 'fullDay', 'name': 'Полный день'}
3               {'id': 'fullDay', 'name': 'Полный день'}
4               {'id': 'fullDay', 'name': 'Полный день'}
                              ...                       
30067           {'id': 'fullDay', 'name': 'Полный день'}
30068           {'id': 'fullDay', 'name': 'Полный день'}
30069           {'id': 'fullDay', 'name': 'Полный день'}
30070        {'id': 'flexible', 'name': 'Гибкий график'}
30071           {'id': 'fullDay', 'name': 'Полный день'}
Name: schedule, Length: 30072, dtype: object

In [ ]:
import json
import re

In [ ]:
def get_emp(x):
    res = re.findall(r"'name': [\"']([^']+)[\"']", x)
    if res == []:
        print(x)
    return res[0]

def get_name(x):
    return json.loads(x.replace("'", '"'))['name']

def data_process(data):
    data['type_schedule'] = data['schedule'].apply(get_name)

    data['city'] = data['area'].apply(get_name)

    data['name_employer'] = data['employer'].apply(get_emp)

    # data['has_contacts'] = data['contacts'].isna()
    # data['has_contacts'] = data['has_contacts'].replace({True: 1, False: 0})


    data['experience_tr'] = data['experience'].apply(get_name)

    return data

In [ ]:
data_train = data_process(data_train)

col_to_drop1 = ['schedule',
              'area',
              'employer',
              'experience']

data_train.drop(columns = col_to_drop1,
         inplace = True)

In [ ]:
data_train

name  \
0                                  Агент по недвижимости   
1                                  IT-специалист/ техник   
2                    Старший/ведущий инженер-программист   
3                   Эксперт / методист приемной комиссии   
4                                   Табельщица/табельщик   
...                                                  ...   
30067                      Руководитель отдела персонала   
30068        Специалист по развитию и обучению персонала   
30069                                Инженер-программист   
30070                                    Куратор проекта   
30071  Консультант / Брокер по коммерческой недвижимости   

                                                 snippet  \
0      {'requirement': 'Уверенное знание компьютера‚ ...   
1      {'requirement': 'Навыки. Коммуникативные навык...   
2      {'requirement': 'Высшее инженерно-техническое ...   
3      {'requirement': 'Высшее образование. Опыт рабо...   
4      {'requirement': 'Знание в совершенстве програм...   
...                                                  ...   
30067  {'requirement': 'Университетское образование в...   
30068  {'requirement': 'Высшее образование. Опыт рабо...   
30069  {'requirement': 'Опыт работы с базами данных, ...   
30070  {'requirement': 'Опыт личных (очных) продаж от...   
30071  {'requirement': 'Высшее образование/ возможнос...   

                                             description  \
0      <p>Мы ищем людей, которым не достаточно того, ...   
1      <ul> </ul> <p><em><strong>Навыки</strong></em>...   
2      <strong>Обязанности:</strong> <ul> <li>Разрабо...   
3      <p>Департамент информационных технологий РХТУ ...   
4      <p><strong>Обязанности:</strong></p> <ul> <li>...   
...                                                  ...   
30067  <strong>Обязанности:</strong> <ul> <li>Управле...   
30068  <p>Группа компаний &quot;Бринэкс&quot; приглаш...   
30069  <strong>Обязанности:</strong> <ul> <li>Разрабо...   
30070  <p><strong>На новый проект крупной российской ...   
30071  <p>Привет!</p> <p>Мы ищем консультанта по комм...   

                                              key_skills  \
0      [{'name': 'Жилая недвижимость'}, {'name': 'Акт...   
1                                                     []   
2      [{'name': 'Linux'}, {'name': 'Bash'}, {'name':...   
3      [{'name': '1С программирование'}, {'name': 'Об...   
4      [{'name': 'Составление отчетности'}, {'name': ...   
...                                                  ...   
30067  [{'name': 'Подбор персонала'}, {'name': 'Адапт...   
30068  [{'name': 'Управление временем'}, {'name': 'Ор...   
30069  [{'name': 'SQL'}, {'name': 'Работа с базами да...   
30070  [{'name': 'Пользователь ПК'}, {'name': 'Работа...   
30071  [{'name': 'Телефонные переговоры'}, {'name': '...   

                                         specializations  \
0      [{'id': '20.20', 'name': 'Агент', 'profarea_id...   
1      [{'id': '1.172', 'name': 'Начальный уровень, М...   
2      [{'id': '1.221', 'name': 'Программирование, Ра...   
3      [{'id': '3.150', 'name': 'Менеджмент продукта ...   
4      [{'id': '18.142', 'name': 'Машиностроение', 'p...   
...                                                  ...   
30067  [{'id': '9.738', 'name': 'Другое', 'profarea_i...   
30068  [{'id': '6.254', 'name': 'Рекрутмент', 'profar...   
30069  [{'id': '1.221', 'name': 'Программирование, Ра...   
30070  [{'id': '1.221', 'name': 'Программирование, Ра...   
30071  [{'id': '17.242', 'name': 'Прямые продажи', 'p...   

                     region  mean_salary   type_schedule              city  \
0           Санкт-Петербург     125000.0   Гибкий график   Санкт-Петербург   
1         Иркутская область      50000.0  Вахтовый метод            Братск   
2        Ростовская область      80000.0     Полный день    Ростов-на-Дону   
3                    Москва     120000.0     Полный день            Москва   
4       Саратовская область      15000.0     Полный день 

In [ ]:
data_train.columns

Index(['name', 'snippet', 'description', 'key_skills', 'specializations',
       'region', 'mean_salary', 'type_schedule', 'city', 'name_employer',
       'experience_tr'],
      dtype='object')

In [ ]:
import ast
from gensim.models import Word2Vec

In [ ]:
# Функция для извлечения всех навыков из строки
def extract_skills(skill_str):
    skills_list = ast.literal_eval(skill_str)
    return [skill['name'] for skill in skills_list]

# Применяем функцию для каждого элемента в столбце "key_skills"
data_train['skills'] = data_train['key_skills'].apply(extract_skills)

# Обучаем модель Word2Vec на скиллах
model = Word2Vec(sentences=data_train['skills'], vector_size=100, window=5, min_count=1, workers=4)

# Функция для получения эмбеддинга для каждого скилла
def get_embeddings(skill_list):
    embs = [model.wv[skill] for skill in skill_list]
    return np.mean(embs, axis = 0)

# Применяем функцию, чтобы получить эмбеддинги для каждого набора скиллов
embeddings = data_train['skills'].apply(get_embeddings)

/usr/local/lib/python3.11/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.11/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


In [ ]:
data_train['key_skills']

0        [{'name': 'Жилая недвижимость'}, {'name': 'Акт...
1                                                       []
2        [{'name': 'Linux'}, {'name': 'Bash'}, {'name':...
3        [{'name': '1С программирование'}, {'name': 'Об...
4        [{'name': 'Составление отчетности'}, {'name': ...
                               ...                        
30067    [{'name': 'Подбор персонала'}, {'name': 'Адапт...
30068    [{'name': 'Управление временем'}, {'name': 'Ор...
30069    [{'name': 'SQL'}, {'name': 'Работа с базами да...
30070    [{'name': 'Пользователь ПК'}, {'name': 'Работа...
30071    [{'name': 'Телефонные переговоры'}, {'name': '...
Name: key_skills, Length: 30072, dtype: object

In [ ]:
def extract_skills(skill_str):
    # Преобразуем строку в список словарей
    skills_list = ast.literal_eval(skill_str)
    # Извлекаем все значения 'name' из списка
    return [skill['name'] for skill in skills_list]

data_train['key_skills'].apply(extract_skills)

0        [Жилая недвижимость, Активные продажи, Подбор ...
1                                                       []
2                                     [Linux, Bash, C/C++]
3        [1С программирование, Обновление конфигурации ...
4        [Составление отчетности, Работа с оргтехникой,...
                               ...                        
30067    [Подбор персонала, Адаптация персонала, Управл...
30068    [Управление временем, Организация тренинга для...
30069           [SQL, Работа с базами данных, Базы данных]
30070    [Пользователь ПК, Работа в команде, Навыки про...
30071    [Телефонные переговоры, Деловая переписка, Пои...
Name: key_skills, Length: 30072, dtype: object

In [ ]:
data_train['skills']

0        [Жилая недвижимость, Активные продажи, Подбор ...
1                                                       []
2                                     [Linux, Bash, C/C++]
3        [1С программирование, Обновление конфигурации ...
4        [Составление отчетности, Работа с оргтехникой,...
                               ...                        
30067    [Подбор персонала, Адаптация персонала, Управл...
30068    [Управление временем, Организация тренинга для...
30069           [SQL, Работа с базами данных, Базы данных]
30070    [Пользователь ПК, Работа в команде, Навыки про...
30071    [Телефонные переговоры, Деловая переписка, Пои...
Name: skills, Length: 30072, dtype: object

In [ ]:
def extract_skills(skill_str):
    # Преобразуем строку в список словарей
    skills_list = ast.literal_eval(skill_str)
    # Извлекаем все значения 'name' из списка
    return [skill['name'] for skill in skills_list]

# Применяем функцию для каждого элемента в столбце "skills"
data_train['skills'] = data_train['key_skills'].apply(extract_skills)

# Извлекаем все уникальные навыки из всех записей
all_skills = set([skill for sublist in data_train['skills'] for skill in sublist])

# Создаем новые столбцы для каждого навыка

for skill in all_skills:
    data_train[skill] = data_train['skills'].apply(lambda x: 1 if skill in x else 0)

data_train

Streaming output truncated to the last 5000 lines.
<ipython-input-15-a92b5dfc7166>:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_train[skill] = data_train['skills'].apply(lambda x: 1 if skill in x else 0)
<ipython-input-15-a92b5dfc7166>:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_train[skill] = data_train['skills'].apply(lambda x: 1 if skill in x else 0)
<ipython-input-15-a92b5dfc7166>:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, whi

name  \
0                                  Агент по недвижимости   
1                                  IT-специалист/ техник   
2                    Старший/ведущий инженер-программист   
3                   Эксперт / методист приемной комиссии   
4                                   Табельщица/табельщик   
...                                                  ...   
30067                      Руководитель отдела персонала   
30068        Специалист по развитию и обучению персонала   
30069                                Инженер-программист   
30070                                    Куратор проекта   
30071  Консультант / Брокер по коммерческой недвижимости   

                                                 snippet  \
0      {'requirement': 'Уверенное знание компьютера‚ ...   
1      {'requirement': 'Навыки. Коммуникативные навык...   
2      {'requirement': 'Высшее инженерно-техническое ...   
3      {'requirement': 'Высшее образование. Опыт рабо...   
4      {'requirement': 'Знание в совершенстве програм...   
...                                                  ...   
30067  {'requirement': 'Университетское образование в...   
30068  {'requirement': 'Высшее образование. Опыт рабо...   
30069  {'requirement': 'Опыт работы с базами данных, ...   
30070  {'requirement': 'Опыт личных (очных) продаж от...   
30071  {'requirement': 'Высшее образование/ возможнос...   

                                             description  \
0      <p>Мы ищем людей, которым не достаточно того, ...   
1      <ul> </ul> <p><em><strong>Навыки</strong></em>...   
2      <strong>Обязанности:</strong> <ul> <li>Разрабо...   
3      <p>Департамент информационных технологий РХТУ ...   
4      <p><strong>Обязанности:</strong></p> <ul> <li>...   
...                                                  ...   
30067  <strong>Обязанности:</strong> <ul> <li>Управле...   
30068  <p>Группа компаний &quot;Бринэкс&quot; приглаш...   
30069  <strong>Обязанности:</strong> <ul> <li>Разрабо...   
30070  <p><strong>На новый проект крупной российской ...   
30071  <p>Привет!</p> <p>Мы ищем консультанта по комм...   

                                              key_skills  \
0      [{'name': 'Жилая недвижимость'}, {'name': 'Акт...   
1                                                     []   
2      [{'name': 'Linux'}, {'name': 'Bash'}, {'name':...   
3      [{'name': '1С программирование'}, {'name': 'Об...   
4      [{'name': 'Составление отчетности'}, {'name': ...   
...                                                  ...   
30067  [{'name': 'Подбор персонала'}, {'name': 'Адапт...   
30068  [{'name': 'Управление временем'}, {'name': 'Ор...   
30069  [{'name': 'SQL'}, {'name': 'Работа с базами да...   
30070  [{'name': 'Пользователь ПК'}, {'name': 'Работа...   
30071  [{'name': 'Телефонные переговоры'}, {'name': '...   

                                         specializations  \
0      [{'id': '20.20', 'name': 'Агент', 'profarea_id...   
1      [{'id': '1.172', 'name': 'Начальный уровень, М...   
2      [{'id': '1.221', 'name': 'Программирование, Ра...   
3      [{'id': '3.150', 'name': 'Менеджмент продукта ...   
4      [{'id': '18.142', 'name': 'Машиностроение', 'p...   
...                                                  ...   
30067  [{'id': '9.738', 'name': 'Другое', 'profarea_i...   
30068  [{'id': '6.254', 'name': 'Рекрутмент', 'profar...   
30069  [{'id': '1.221', 'name': 'Программирование, Ра...   
30070  [{'id': '1.221', 'name': 'Программирование, Ра...   
30071  [{'id': '17.242', 'name': 'Прямые продажи', 'p...   

                     region  mean_salary   type_schedule              city  \
0           Санкт-Петербург     125000.0   Гибкий график   Санкт-Петербург   
1         Иркутская область      50000.0  Вахтовый метод            Братск   
2        Ростовская область      80000.0     Полный день    Ростов-на-Дону   
3                    Москва     120000.0     Полный день            Москва   
4       Саратовская область      15000.0     Полный день 

In [ ]:
['key_skills', 'skills',
               'snippet', 'specializations',
              'description']

['key_skills', 'skills', 'snippet', 'specializations', 'description']

In [ ]:
len(data_train['name'].unique())

13521

In [ ]:
len(data_train['name_employer'].unique())

12973

In [ ]:
data_train['experience_tr'].unique()

array(['Нет опыта', 'От 1 года до 3 лет', 'От 3 до 6 лет', 'Более 6 лет'],
      dtype=object)

In [ ]:
data_train['experience_tr'] = data_train['experience_tr'].replace({
    'Нет опыта': '0',
    'От 1 года до 3 лет': '1',
    'От 3 до 6 лет': '2',
    'Более 6 лет': 3
})

In [ ]:
data_train

name  \
0                                  Агент по недвижимости   
1                                  IT-специалист/ техник   
2                    Старший/ведущий инженер-программист   
3                   Эксперт / методист приемной комиссии   
4                                   Табельщица/табельщик   
...                                                  ...   
30067                      Руководитель отдела персонала   
30068        Специалист по развитию и обучению персонала   
30069                                Инженер-программист   
30070                                    Куратор проекта   
30071  Консультант / Брокер по коммерческой недвижимости   

                                                 snippet  \
0      {'requirement': 'Уверенное знание компьютера‚ ...   
1      {'requirement': 'Навыки. Коммуникативные навык...   
2      {'requirement': 'Высшее инженерно-техническое ...   
3      {'requirement': 'Высшее образование. Опыт рабо...   
4      {'requirement': 'Знание в совершенстве програм...   
...                                                  ...   
30067  {'requirement': 'Университетское образование в...   
30068  {'requirement': 'Высшее образование. Опыт рабо...   
30069  {'requirement': 'Опыт работы с базами данных, ...   
30070  {'requirement': 'Опыт личных (очных) продаж от...   
30071  {'requirement': 'Высшее образование/ возможнос...   

                                             description  \
0      <p>Мы ищем людей, которым не достаточно того, ...   
1      <ul> </ul> <p><em><strong>Навыки</strong></em>...   
2      <strong>Обязанности:</strong> <ul> <li>Разрабо...   
3      <p>Департамент информационных технологий РХТУ ...   
4      <p><strong>Обязанности:</strong></p> <ul> <li>...   
...                                                  ...   
30067  <strong>Обязанности:</strong> <ul> <li>Управле...   
30068  <p>Группа компаний &quot;Бринэкс&quot; приглаш...   
30069  <strong>Обязанности:</strong> <ul> <li>Разрабо...   
30070  <p><strong>На новый проект крупной российской ...   
30071  <p>Привет!</p> <p>Мы ищем консультанта по комм...   

                                              key_skills  \
0      [{'name': 'Жилая недвижимость'}, {'name': 'Акт...   
1                                                     []   
2      [{'name': 'Linux'}, {'name': 'Bash'}, {'name':...   
3      [{'name': '1С программирование'}, {'name': 'Об...   
4      [{'name': 'Составление отчетности'}, {'name': ...   
...                                                  ...   
30067  [{'name': 'Подбор персонала'}, {'name': 'Адапт...   
30068  [{'name': 'Управление временем'}, {'name': 'Ор...   
30069  [{'name': 'SQL'}, {'name': 'Работа с базами да...   
30070  [{'name': 'Пользователь ПК'}, {'name': 'Работа...   
30071  [{'name': 'Телефонные переговоры'}, {'name': '...   

                                         specializations  \
0      [{'id': '20.20', 'name': 'Агент', 'profarea_id...   
1      [{'id': '1.172', 'name': 'Начальный уровень, М...   
2      [{'id': '1.221', 'name': 'Программирование, Ра...   
3      [{'id': '3.150', 'name': 'Менеджмент продукта ...   
4      [{'id': '18.142', 'name': 'Машиностроение', 'p...   
...                                                  ...   
30067  [{'id': '9.738', 'name': 'Другое', 'profarea_i...   
30068  [{'id': '6.254', 'name': 'Рекрутмент', 'profar...   
30069  [{'id': '1.221', 'name': 'Программирование, Ра...   
30070  [{'id': '1.221', 'name': 'Программирование, Ра...   
30071  [{'id': '17.242', 'name': 'Прямые продажи', 'p...   

                     region  mean_salary   type_schedule              city  \
0           Санкт-Петербург     125000.0   Гибкий график   Санкт-Петербург   
1         Иркутская область      50000.0  Вахтовый метод            Братск   
2        Ростовская область      80000.0     Полный день    Ростов-на-Дону   
3                    Москва     120000.0     Полный день            Москва   
4       Саратовская область      15000.0     Полный день 

In [ ]:
data_train.drop(['key_skills', 'skills'], axis=1, inplace=True)
data_train_f = data_train.drop(['snippet', 'description', 'specializations', 'region'], axis=1)
data_train_f['experience_tr'] =pd.to_numeric(data_train_f['experience_tr'])
data_train_f

name  mean_salary  \
0                                  Агент по недвижимости     125000.0   
1                                  IT-специалист/ техник      50000.0   
2                    Старший/ведущий инженер-программист      80000.0   
3                   Эксперт / методист приемной комиссии     120000.0   
4                                   Табельщица/табельщик      15000.0   
...                                                  ...          ...   
30067                      Руководитель отдела персонала     190000.0   
30068        Специалист по развитию и обучению персонала      45000.0   
30069                                Инженер-программист      75000.0   
30070                                    Куратор проекта      30000.0   
30071  Консультант / Брокер по коммерческой недвижимости     100000.0   

        type_schedule              city  \
0       Гибкий график   Санкт-Петербург   
1      Вахтовый метод            Братск   
2         Полный день    Ростов-на-Дону   
3         Полный день            Москва   
4         Полный день           Энгельс   
...               ...               ...   
30067     Полный день            Москва   
30068     Полный день  Набережные Челны   
30069     Полный день      Магнитогорск   
30070   Гибкий график      Екатеринбург   
30071     Полный день            Москва   

                                  name_employer  experience_tr  Stock market  \
0                                          АРИН              0             0   
1                                        СМП-38              1             0   
2                                   САРМАТ, НПП              1             0   
3                      РХТУ им. Д.И. Менделеева              1             0   
4                       Сигнал, группа компаний              1             0   
...                                         ...            ...           ...   
30067                                  СИНЕРГИЯ              3             0   
30068                                    Brinex              1             0   
30069  Магнитогорский металлургический комбинат              1             0   
30070                                     ANCOR              1             0   
30071        Bright Rich | CORFAC International              0             0   

       работа со статистикой  Сквозная аналитика  \
0                          0                   0   
1                          0                   0   
2                          0                   0   
3                          0                   0   
4                          0                   0   
...                      ...                 ...   
30067                      0                   0   
30068                      0                   0   
30069                      0                   0   
30070                      0                   0   
30071                      0                   0   

       3. Навыки межличностного делового общения.  ...  Публичные выступления  \
0                                               0  ...                      0   
1                                               0  ...                      0   
2                                               0  ...                      0   
3                                               0  ...                      0   
4                                               0  ...                      0   
...                                           ...  ...                    ...   
30067                                           0  ...                      0   
30068                                           0  ...                      0   
30069                                           0  ...                      0   
30070                                           0  ...                      0   
30071                                           0  ...                      0   

       GitLab  3D Ceramics  Pentaho  Дизайн полиграфии  \
0           0            0        0      

In [ ]:
X = data_train_f.drop(columns=["mean_salary"])
y = data_train_f["mean_salary"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)

In [ ]:
X_train

name   type_schedule  \
7274   Заместитель руководителя отдела мотивации и оп...     Полный день   
4826                         Web UI/UX-дизайнер (Middle)     Полный день   
15965                                Программист Битрикс     Полный день   
13647                     Агент по продажам недвижимости     Полный день   
13177                        Менеджер по персоналу (КДП)     Полный день   
...                                                  ...             ...   
28017                                            Риелтор   Гибкий график   
17728      Агент по недвижимости (начинающий специалист)     Полный день   
29199      Координатор проекта в аутсорсинговую компанию     Полный день   
7293                                Спасатель-инструктор     Полный день   
17673                              Менеджер по персоналу  Сменный график   

                  city                 name_employer  experience_tr  \
7274       Владивосток         Агентство КИТ Консалт              3   
4826            Москва      Интеллектуальные Системы              1   
15965   Ростов-на-Дону       Mibok,  Internet Agency              1   
13647             Сочи  Агентство недвижимости АТЛАС              0   
13177           Москва                     Рк-Сервис              1   
...                ...                           ...            ...   
28017           Москва            ИНКОМ-НЕДВИЖИМОСТЬ              0   
17728           Ковров            АЮВЕЛ НЕДВИЖИМОСТЬ              0   
29199     Екатеринбург             Ресурс Менеджмент              1   
7293   Санкт-Петербург     Комплекс отдыха Семь Озер              1   
17673              Уфа                      ПТ-Групп              0   

       Stock market  работа со статистикой  Сквозная аналитика  \
7274              0                      0                   0   
4826              0                      0                   0   
15965             0                      0                   0   
13647             0                      0                   0   
13177             0                      0                   0   
...             ...                    ...                 ...   
28017             0                      0                   0   
17728             0                      0                   0   
29199             0                      0                   0   
7293              0                      0                   0   
17673             0                      0                   0   

       3. Навыки межличностного делового общения.  BOSCH  ...  \
7274                                            0      0  ...   
4826                                            0      0  ...   
15965                                           0      0  ...   
13647                                           0      0  ...   
13177                                           0      0  ...   
...                                           ...    ...  ...   
28017                                           0      0  ...   
17728                                           0      0  ...   
29199                                           0      0  ...   
7293                                            0      0  ...   
17673                                           0      0  ...   

       Публичные выступления  GitLab  3D Ceramics  Pentaho  Дизайн полиграфии  \
7274                       0       0            0        0                  0   
4826                       0       0            0        0                  0   
15965                      0       0            0        0                  0   
13647                      0       0            0        0                  0   
13177                      0       0            0        0                  0   
...                      ...     ...          ...      ...                ...   
28017                      0       0            0        0                  0   
17728                      0       0            0        0      

In [ ]:
categorical = list(X_train.dtypes[X_train.dtypes == "object"].index)
categorical

['name', 'type_schedule', 'city', 'name_employer']

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge


lin_reg = MyLinearRegression(weight_calc = 'sgd',
                           alpha=1e-2,
                           max_iter=5000,
                            early_stopping=0.0001 ,
                            lambda_1=0.01,
                            lambda_2=0.01,
                            regularization='l1l2',
                          batch_size = 32)

column_transformer = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='first'), categorical)
    ],
    remainder='passthrough'  # Оставляем все остальные колонки (если они есть) без изменений
)

pipeline = Pipeline([
    ('transformer', column_transformer),
    ('regressor',  lin_reg)  # Используем ваш класс MyLinearRegression
])

In [ ]:
model = pipeline.fit(X_train, y_train)

100%|██████████| 5000/5000 [06:17<00:00, 13.25it/s]


In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [ ]:
y_train_pred = model.predict(X_train)
y_pred = model.predict(X_test)

print("Test MSE = %.4f" % mean_squared_error(y_test, y_pred))
print('Test MAE = %.4f' % mean_absolute_error(y_test, y_pred) )
print('Test R2 = %.4f' % r2_score(y_test, y_pred) )
print("Train MSE = %.4f" % mean_squared_error(y_train, y_train_pred))
print('Train MAE = %.4f' % mean_absolute_error(y_train, y_train_pred) )
print('Train R2 = %.4f' % r2_score(y_train, y_train_pred) )

X=  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
coeff=  [ 5.50538624e+01 -4.47009546e+01 -1.19145754e+02 ... -8.27352456e+01
 -2.90609384e+02  4.17969230e-05]
intercept=  45856.14964830249
type X=  <class 'numpy.ndarray'>
type coeff=  <class 'numpy.ndarray'>
type intercept=  <class 'numpy.float64'>
shape X=  (21050, 28727)
shape coeff=  (28727,)
shape intercept=  ()


/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 2, 3] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


X=  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
coeff=  [ 5.50538624e+01 -4.47009546e+01 -1.19145754e+02 ... -8.27352456e+01
 -2.90609384e+02  4.17969230e-05]
intercept=  45856.14964830249
type X=  <class 'numpy.ndarray'>
type coeff=  <class 'numpy.ndarray'>
type intercept=  <class 'numpy.float64'>
shape X=  (9022, 28727)
shape coeff=  (28727,)
shape intercept=  ()
Test MSE = 7033131578.2522
Test MAE = 41265.3624
Test R2 = 0.3431
Train MSE = 6907905178.5970
Train MAE = 40864.9362
Train R2 = 0.3744


In [ ]:
example = pd.read_csv('Sample_Submission.csv')
test_orig = pd.read_csv('for_prediction.csv')

In [ ]:
test_orig.drop(columns = ['Id'],
         inplace = True)

In [ ]:
test = test_orig.copy()

In [ ]:
class_drop = ['premium', 'department', 'has_test', 'response_letter_required',
                     'working_days', 'working_time_intervals', 'working_time_modes',
                     'immediate_redirect_url', 'published_at', 'created_at',
                     'response_url', 'sort_point_distance', 'archived', 'insider_interview',
                    'url', 'alternate_url', 'relations', 'type', 'address',
                    'accept_temporary']

test.drop(columns = class_drop,
         inplace = True)

In [ ]:
test =  data_process(test)

In [ ]:
def extract_skills(skill_str):
    # Преобразуем строку в список словарей
    skills_list = ast.literal_eval(skill_str)
    # Извлекаем все значения 'name' из списка
    return [skill['name'] for skill in skills_list]

# Применяем функцию для каждого элемента в столбце "skills"
test['skills'] = test['key_skills'].apply(extract_skills)

# Извлекаем все уникальные навыки из всех записей
all_skills = set([skill for sublist in test['skills'] for skill in sublist])

# Создаем новые столбцы для каждого навыка
for skill in all_skills:
    test[skill] = test['skills'].apply(lambda x: 1 if skill in x else 0)

Streaming output truncated to the last 5000 lines.
<ipython-input-81-f6aebeee25be>:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[skill] = test['skills'].apply(lambda x: 1 if skill in x else 0)
<ipython-input-81-f6aebeee25be>:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[skill] = test['skills'].apply(lambda x: 1 if skill in x else 0)
<ipython-input-81-f6aebeee25be>:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.

In [ ]:
col_to_drop1 = ['schedule',
              'area',
              'employer',
              'contacts',
              'experience']
col_to_drop2 = ['key_skills', 'skills',
               'snippet', 'specializations',
              'description']

test.drop(columns = col_to_drop1,
         inplace = True)

test.drop(columns = col_to_drop2,
         inplace = True)

In [ ]:
for col in X_train:
    if col not in test:
        test[col] = 0

Streaming output truncated to the last 5000 lines.
<ipython-input-83-1dd043347f69>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
<ipython-input-83-1dd043347f69>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
<ipython-input-83-1dd043347f69>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newfra

In [ ]:
test.dropna()

name  \
0                                  Помощник маркетолога   
1                                 Менеджер по персоналу   
2     Инструктор на детскую игровую площадку (ТЦ "Ме...   
3                                    Программист Delphi   
4                                Ведущий специалист ВКС   
...                                                 ...   
7513                                        HR менеджер   
7514                             Руководитель HR отдела   
7515                        Системный аналитик (Стажер)   
7516  Руководитель Отдела развития банковских технол...   
7517  Старший специалист по Информационной Безопасности   

                       region     type_schedule             city  \
0                      Москва  Удаленная работа           Москва   
1             Санкт-Петербург       Полный день  Санкт-Петербург   
2     Республика Башкортостан       Полный день              Уфа   
3       Новосибирская область  Удаленная работа      Новосибирск   
4                      Москва       Полный день           Москва   
...                       ...               ...              ...   
7513          Республика Крым       Полный день      Симферополь   
7514                   Москва       Полный день           Москва   
7515     Свердловская область     Гибкий график     Екатеринбург   
7516          Приморский край       Полный день      Владивосток   
7517                   Москва       Полный день           Москва   

                                          name_employer       experience_tr  \
0                                              EKO BIKE  От 1 года до 3 лет   
1                       Ваш дом, агентство недвижимости           Нет опыта   
2                                             Мегаполис           Нет опыта   
3                                          AMS Software       От 3 до 6 лет   
4                                              Технокад  От 1 года до 3 лет   
...                                                 ...                 ...   
7513                   Группа компаний Shels (ООО Шелс)  От 1 года до 3 лет   
7514                                             Edison  От 1 года до 3 лет   
7515                                         Альфа-Банк           Нет опыта   
7516                           СКБ Приморья Примсоцбанк  От 1 года до 3 лет   
7517  Управление ВОЛС-ВЛ (Дочернее Общество ПАО Росс...       От 3 до 6 лет   

      3D  Quarkus  NuxtJS  Финансовое планирование  ...  Cycle  Единоборства  \
0      0        0       0                        0  ...      0             0   
1      0        0       0                        0  ...      0             0   
2      0        0       0                        0  ...      0             0   
3      0        0       0                        0  ...      0             0   
4      0        0       0                        0  ...      0             0   
...   ..      ...     ...                      ...  ...    ...           ...   
7513   0        0       0                        0  ...      0             0   
7514   0        0       0                        0  ...      0             0   
7515   0        0       0                        0  ...      0             0   
7516   0        0       0                        0  ...      0             0   
7517   0        0       0                        0  ...      0             0   

      Yii 2  поиск кандидатов  Grid  Бюджетные и автономные учреждения  \
0         0                 0     0                                  0   
1         0                 0     0                                  0   
2         0                 0     0                                  0   
3         0                 0     0                                  0   
4         0                 0     0                                  0   
...     ...               ...   ...                                ...   
7513      0                 0     0                                  0   
7514      0            

In [ ]:
test['experience_tr'] = test['experience_tr'].replace({
    'Нет опыта': '0',
    'От 1 года до 3 лет': '1',
    'От 3 до 6 лет': '2',
    'Более 6 лет': 3
})

In [ ]:
test[test.select_dtypes(include=np.number).columns] = test[test.select_dtypes(include=np.number).columns].astype('float')

In [ ]:
test.shape

(7518, 8703)

In [ ]:
y_pred = model.predict(X_test)

X=  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
coeff=  [ 6.40898981e+00  4.51827835e+01 -1.04806988e+02 ...  1.30814257e+02
 -5.41022106e+02 -5.35253235e-05]
intercept=  46499.21765033995
type X=  <class 'numpy.ndarray'>
type coeff=  <class 'numpy.ndarray'>
type intercept=  <class 'numpy.float64'>
shape X=  (9022, 28731)
shape coeff=  (28731,)
shape intercept=  ()


In [ ]:
predss = model.predict(test)

X=  [[0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 ...
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]]
coeff=  [ 6.40898981e+00  4.51827835e+01 -1.04806988e+02 ...  1.30814257e+02
 -5.41022106e+02 -5.35253235e-05]
intercept=  46499.21765033995
type X=  <class 'numpy.ndarray'>
type coeff=  <class 'numpy.ndarray'>
type intercept=  <class 'numpy.float64'>
shape X=  (7518, 28731)
shape coeff=  (28731,)
shape intercept=  ()


In [ ]:
# ct = column_transformer

# ct.fit(X_train)

# test_ = ct.transform(test)
# test_.shape

(7518, 28731)

In [ ]:
example['Predicted'] = predss

In [ ]:
example.to_csv('predictions.csv', index = False)

In [ ]:
data_train['mean_salary'].mean()

97728.25091447194